### PR TITLE
EE SIO Support

### PR DESCRIPTION
**Pull request by israpps**
Allows logging into the EE UART

### CODE REVIEW

**Comment by Wolf3s** [comment]
isra clang-format the code please.

**Comment by h4570** [comment]
Pretty cool feature.
Thank you for contribution.

Did you tested it already?
Proofs are appreciated.

**Comment by israpps** [comment]
> isra clang-format the code please.

Not at the PC until tomorrow night.

***

> Pretty cool feature. Thank you for contribution.
> 
> Did you tested it already? Proofs are appreciated.

Haven't tested it yet, but I made the siocookie library, and I've used EESIO before, so it should work...
But I'll try as soon as I can.

It can also be tested on emulator, EE SIO printf is printed on blue text

**Comment by h4570** [comment]
Please merge latest master to this branch.
Thanks!

**Comment by Wolf3s** [comment]
@israpps why close this?

**Comment by israpps** [comment]
> @israpps why close this?

Will make it from scratch
The PR was based on your fork, not upstream

**Pull request closed without merging**
