### PR TITLE
Fixed loading erros in .obj loader when loading models without UVMap or Normals.

### LINKED ISSUE #20: Improve obj loader
@Foxar please describe the needs if you could.

https://github.com/h4570/tyra/blob/d58163d75be2d6c848f4456f73cebd8a6c1a63bd/src/engine/include/loaders/obj_loader.hpp#L18

### PR DESCRIPTION
**Pull request by Foxar**
This should resolve #20 as I understand it.

### CODE REVIEW

**Comment by h4570** [comment]
Great.
Did you tested it already? I mean putting obj without uv/st and normals

**Comment by Foxar** [comment]
Crap. I just tested it and indeed, in one case it still doesn't work. Wait with this PR until i throw in one extra commit when I fix this

**Comment by h4570** [comment]
Please always do the test, before PRing

**Comment by Foxar** [comment]
Fixed. Please re-review.

**Pull request merged**
